# Generated by Django 4.1 on 2023-04-05 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Capacity', models.IntegerField()),
                ('Room_Description', models.TextField(max_length=500)),
                ('Room_Price', models.FloatField()),
                ('Room_Image', models.ImageField(blank=True, null=True, upload_to='Room_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_1', models.CharField(max_length=50)),
                ('test_Description', models.TextField(max_length=500)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_age', models.IntegerField(blank=True, default=18, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_contact_number', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor_Number', models.IntegerField()),
                ('Room_Status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Unavailable', 'Unavailable')], default='Available', max_length=11)),
                ('Room_Type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='innstant.roomtype')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('payment_due_date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('tenant', models.CharField(max_length=500)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_payment', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_payment', to='innstant.room')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_type', to='innstant.complainttype')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='innstant.complaint')),
                ('user_comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('tenant_sign', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('landlord_sign', models.ImageField(upload_to='signatures/')),
                ('test_date', models.DateField()),
                ('landlord', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_contract', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
