# Generated by Django 4.1 on 2023-04-07 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innstant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_payment', to=settings.AUTH_USER_MODEL),
        ),
    ]
