# Generated by Django 4.1 on 2023-04-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0004_alter_payment_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='innstant.rules'),
        ),
    ]
