# Generated by Django 4.1 on 2023-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0006_remove_agreement_rules_roomtype_room_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_legend',
            field=models.CharField(default='', max_length=20),
        ),
    ]
