# Generated by Django 4.1 on 2023-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0007_alter_roomtype_room_legend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='Room_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
