# Generated by Django 4.1 on 2023-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0009_alter_roomtype_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='Room_Description',
            field=models.TextField(max_length=500),
        ),
    ]
