# Generated by Django 4.1 on 2023-04-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0010_alter_roomtype_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
