# Generated by Django 4.1 on 2023-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0011_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extended_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
