# Generated by Django 4.1 on 2023-04-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0012_payment_extended_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='extended_due_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='extension_duration',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 day'), (7, '1 week'), (30, '1 month')], null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='extension_requested',
            field=models.BooleanField(default=False),
        ),
    ]
