# Generated by Django 4.1 on 2023-04-21 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('innstant', '0013_remove_payment_extended_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='extension_duration',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='extension_requested',
        ),
        migrations.CreateModel(
            name='ExtendStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1M', '1 month'), ('1W', '1 week'), ('1D', '1 day')], max_length=2)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='extendStay_room', to='innstant.room')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='extendStay_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
