# Generated by Django 4.1 on 2023-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0022_notification_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendstay',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
