# Generated by Django 4.1 on 2023-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0025_remove_notification_status_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
