# Generated by Django 4.1 on 2023-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0026_notification_is_read_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='poke',
            field=models.BooleanField(default=False),
        ),
    ]
