# Generated by Django 4.1 on 2023-04-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0028_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
