# Generated by Django 4.1 on 2023-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0029_alter_footer_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='Contact',
            new_name='Contact1',
        ),
        migrations.AddField(
            model_name='footer',
            name='Contact2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footer',
            name='Landline',
            field=models.IntegerField(default=0),
        ),
    ]
