# Generated by Django 4.1 on 2023-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0030_rename_contact_footer_contact1_footer_contact2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='About',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Contact1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Contact2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Email_us',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Landline',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
