# Generated by Django 4.1 on 2023-05-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0031_alter_footer_about_alter_footer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendstay',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
    ]
