# Generated by Django 4.1 on 2023-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0032_extendstay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendstay',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extendstay',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Processing', 'Processing')], default='Pending', max_length=10),
        ),
    ]
