# Generated by Django 4.1 on 2023-05-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0033_extendstay_submitted_alter_extendstay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendstay',
            name='submitted',
        ),
    ]
