# Generated by Django 4.1 on 2023-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0034_remove_extendstay_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='About_2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
