# Generated by Django 4.1 on 2023-05-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0035_footer_about_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='About_2',
            new_name='About_innstant',
        ),
    ]
