# Generated by Django 4.1 on 2023-05-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0036_rename_about_2_footer_about_innstant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='About_innstant',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
