# Generated by Django 4.1 on 2023-05-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0037_alter_footer_about_innstant'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCODEPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRCODE_Name', models.CharField(default='', max_length=20)),
                ('QRCODE', models.ImageField(blank=True, null=True, upload_to='QRCODEPayment/')),
            ],
        ),
    ]
