# Generated by Django 4.1 on 2023-05-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0038_qrcodepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='Contact1',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Contact2',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='Landline',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tenantinfo',
            name='contact_number',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tenantinfo',
            name='guardian_contact_number',
            field=models.CharField(blank=True, default='00000000000', max_length=11, null=True),
        ),
    ]
