# Generated by Django 4.1 on 2023-05-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innstant', '0039_alter_footer_contact1_alter_footer_contact2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
